---
- name: "debug: Config Light"
  vars:
    msg: |
      ansible_os_family [{{ ansible_os_family }}]
      ansible_distribution [{{ ansible_distribution }}]
      ansible_distribution_major_version [{{ ansible_distribution_major_version }}]
      ansible_distribution_version [{{ ansible_distribution_version }}]
      ansible_distribution_release [{{ ansible_distribution_release }}]

      cl_backup [{{ cl_backup }}]
      cl_packages
      {{ cl_packages|to_yaml }}
      cl_services
      {{ cl_services|to_yaml }}
      cl_files
      {{ cl_files|to_nice_yaml }}

      install_retries [{{ install_retries }}]
      install_delay [{{ install_delay }}]

      freebsd_install_method [{{ freebsd_install_method }}]
      freebsd_use_packages [{{ freebsd_use_packages }}]

  debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
