---

- name: "files-inifile: INI files"
  ini_file:
    path: "{{ item.0.path }}"
    owner: "{{ item.0.owner|default(omit) }}"
    group: "{{ item.0.group|default(omit) }}"
    mode: "{{ item.0.mode|default(omit) }}"
    create: "{{ item.0.create|default(omit) }}"
    allow_no_value: "{{ item.0.allow_no_value|default(omit) }}"
    attributes: "{{ item.0.attributes|default(omit) }}"
    no_extra_spaces: "{{ item.0.no_extra_spaces|default(omit) }}"
    section: "{{ item.1.section }}"
    state: "{{ item.1.state|default(omit) }}"
    option: "{{ item.1.option|default(omit) }}"
    value: "{{ item.1.value|default(omit) }}"
    backup: "{{ cl_backup }}"
  loop: "{{ cl_files.values()|list|subelements('ini', {'skip_missing': True}) }}"
  loop_control:
    label: "{{ item.0.path }}"
  notify: "{{ item.0.handlers|default(omit) }}"
  register: cl_results_ini

- name: "files-inifile: Debug"
  block:
    - name: Debug cl_results_ini
      debug:
        var: cl_results_ini
    - name: Debug changed ini paths
      debug:
        msg: "{{ cl_results_ini.results|default([])|
                 json_query('[?changed].invocation.module_args.path')
                 }}"
  when: cl_debug|bool

# EOF
...
