---
# TODO: Complete parameters
- name: "files-lineinfile: Lineinfile"
  lineinfile:
    path: "{{ item.0.path }}"
    regexp: "{{ item.1.regexp }}"
    line: "{{ item.1.line }}"
    owner: "{{ item.0.owner|default(omit) }}"
    group: "{{ item.0.group|default(omit) }}"
    mode: "{{ item.0.mode|default(omit) }}"
    create: "{{ item.0.create|default(omit) }}"
    validate: "{{ item.0.validate|default(omit) }}"
  loop: "{{ cl_files.values()|subelements('lines', skip_missing=true) }}"
  loop_control:
    label: "{{ item.0.path }}"
  notify: "{{ item.0.handlers|default(omit) }}"
  register: cl_results_lines

- name: "files-lineinfile: Debug"
  block:
    - name: Debug cl_results_lines
      debug:
        var: cl_results_lines
    - name: Debug changed lines paths
      debug:
        msg: "{{ cl_results_lines.results|default([])|
                 json_query('[?changed==`true`].invocation.module_args.path')
                 }}"
  when: cl_debug|bool

# EOF
...
