---

- name: "files-delete-backup: Delete backup files that did not change"
  file:
    state: absent
    path: "{{ item }}_{{ cl_timestamp }}.bak"
  loop: "{{ cl_files.values()|list|json_query('[].path')|
            difference(cl_results_copy.results|default([])|
                       json_query('[?changed].invocation.module_args.path'))|unique|
            difference(cl_results_template.results|default([])|
                       json_query('[?changed].invocation.module_args.path'))|unique|
            difference(cl_results_lines.results|default([])|
                       json_query('[?changed].invocation.module_args.path'))|unique|
            difference(cl_results_blocks.results|default([])|
                       json_query('[?changed].invocation.module_args.path'))|unique|
            difference(cl_results_inifile.results|default([])|
                       json_query('[?changed].invocation.module_args.path'))|unique|
            difference(cl_results_patch.results|default([])|
                       json_query('[?changed].invocation.module_args.path'))|unique
            }}"
  when:
    - cl_backup|bool
    - not ansible_check_mode
  changed_when: false

# EOF
...
