---
# TODO: Complete parameters
- name: "files-blockinfile: Blockinfile"
  blockinfile:
    path: "{{ item.0.path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.1.marker }}"
    block: "{{ item.1.block }}"
    owner: "{{ item.0.owner|default(omit) }}"
    group: "{{ item.0.group|default(omit) }}"
    mode: "{{ item.0.mode|default(omit) }}"
    create: "{{ item.0.create|default(omit) }}"
    validate: "{{ item.0.validate|default(omit) }}"
    # backup: "{{ cl_backup }}"
  loop: "{{ cl_files.values()|subelements('blocks', skip_missing=true) }}"
  loop_control:
    label: "{{ item.0.path }}"
  notify: "{{ item.0.handlers|default(omit) }}"
  register: cl_results_blocks

- name: "files-blockinfile: Debug"
  block:
    - name: Debug cl_results_blocks
      debug:
        var: cl_results_blocks
    - name: Debug changed blocks paths
      debug:
        msg: "{{ cl_results_blocks.results|default([])|
                 json_query('[?changed==`true`].invocation.module_args.path')
                 }}"
  when: cl_debug|bool

# EOF
...
