---

- name: "files-ucl: Debug ucl in cl_files.values()"
  ansible.builtin.debug:
    msg: "{{ cl_files.values()|selectattr('ucl', 'defined')|list }}"
  when: cl_debug|bool

- name: "files-ucl: UCL files cl_files.values()"
  vbotka.freebsd.ucl:
    path: "{{ item.0.path }}"
    chdir: "{{ item.1.chdir|default(omit) }}"
    upath: "{{ item.1.upath|default(omit) }}"
    ipath: "{{ item.1.ipath|default(omit) }}"
    icontent: "{{ item.1.icontent|default(omit) }}"
    value: "{{ item.1.value|default(omit) }}"
    vtype: "{{ item.1.vtype|default(omit) }}"
    merge: "{{ item.1.merge|default(omit) }}"
    state: "{{ item.1.state|default(omit) }}"
    delimiter: "{{ item.1.delimiter|default(omit) }}"
    lang: "{{ item.1.lang|default(omit) }}"
    owner: "{{ item.0.owner|default(omit) }}"
    group: "{{ item.0.group|default(omit) }}"
    mode: "{{ item.0.mode|default(omit) }}"
    attributes: "{{ item.0.attributes|default(omit) }}"
    create: "{{ item.0.create|default(omit) }}"
    validate: "{{ item.0.validate|default(omit) }}"
    # backup: "{{ cl_backup }}"
  loop: "{{ cl_files.values()|list|subelements('ucl', skip_missing=true) }}"
  loop_control:
    label: "{{ item.0.path }}"
  notify: "{{ item.0.handlers|default(omit) }}"
  register: cl_results_ucl

- block:
    - name: "files-ucl: Debug cl_results_ucl"
      ansible.builtin.debug:
        var: cl_results_ucl
    - name: "files-ucl: Debug changed ucl paths"
      ansible.builtin.debug:
        msg: "{{ cl_results_ucl.results|default([])|
                 json_query('[?changed].invocation.module_args.path') }}"
  when: cl_debug|bool

# EOF
...
