---

- name: "file-create-backup: Create time-stamp"
  set_fact:
    cl_timestamp: "{{ '%Y-%m-%d_%H_%M_%S'|strftime }}"

- name: "file-create-backup: Stat cl_files"
  stat:
    path: "{{ item }}"
  loop: "{{ cl_files.values()|map(attribute='path')|list|unique }}"
  loop_control:
    label: "{{ item }}"
  register: result

- name: "file-create-backup: Debug result"
  debug:
    var: result
  when: cl_debug|bool

- name: "file-create-backup: Create backup files"
  copy:
    remote_src: true
    src: "{{ item.item }}"
    dest: "{{ item.item }}_{{ cl_timestamp }}.bak"
    mode: preserve
  loop: "{{ result.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.stat.exists
  changed_when: false

# EOF
...
