---
- name: "files-delete-backup: Delete backup files that did not change"
  when: cl_backup|bool
  file:
    state: absent
    path: "{{ item }}_{{ cl_timestamp }}.bak"
  loop: "{{ cl_files.values()|json_query('[].path')|
            difference(
            cl_results_template.results|default([])|
            json_query('[?changed==`true`].invocation.module_args.path'))|
            difference(
            cl_results_lines.results|default([])|
            json_query('[?changed==`true`].invocation.module_args.path'))|
            difference(
            cl_results_blocks.results|default([])|
            json_query('[?changed==`true`].invocation.module_args.path'))|
            difference(
            cl_results_inifile.results|default([])|
            json_query('[?changed==`true`].invocation.module_args.path'))
            }}"
  changed_when: false

# EOF
...
