---
# tasks for config_light

- name: Setup
  ansible.builtin.import_tasks: setup.yml
  when: cl_setup | bool
  delegate_to: localhost
  run_once: true
  tags: [cl_setup, always]

- name: Vars
  ansible.builtin.import_tasks: vars.yml
  tags: [cl_vars, always]

- name: Sanity
  ansible.builtin.import_tasks: sanity.yml
  when: cl_sanity | bool
  delegate_to: localhost
  run_once: true
  tags: [cl_sanity, always]

- name: Debug
  ansible.builtin.import_tasks: debug.yml
  when: cl_debug | bool
  tags: cl_debug

- name: Packages
  ansible.builtin.import_tasks: packages.yml
  when: cl_install | bool
  tags: cl_packages

- name: States
  ansible.builtin.import_tasks: states.yml
  tags: cl_states

- name: Files
  ansible.builtin.import_tasks: files.yml
  tags: cl_files

- name: Services
  ansible.builtin.import_tasks: services.yml
  tags: cl_services

# EOF
