---
# tasks for config_light

- import_tasks: sanity.yml
  when: cl_sanity|bool
  tags: [cl_sanity, always]

- import_tasks: setup.yml
  when: cl_setup|bool
  delegate_to: localhost
  run_once: true
  tags: [cl_setup, always]

- import_tasks: vars.yml
  tags: [cl_vars, always]

- import_tasks: debug.yml
  when: cl_debug|bool
  tags: [cl_debug, always]

- import_tasks: packages.yml
  tags: cl_packages

- import_tasks: files.yml
  tags: cl_files

- import_tasks: services.yml
  tags: cl_services

# EOF
...
