---
# tasks for config_light

- import_tasks: vars.yml
  tags: [cl_vars, always]

- import_tasks: debug.yml
  when: cl_debug|bool
  tags: [cl_debug, always]

- import_tasks: packages.yml
  tags: cl_packages

- import_tasks: files.yml
  tags: cl_files

- import_tasks: services.yml
  tags: cl_services

# EOF
...
