---
# tasks for config_light

- name: Setup, create vars, and test sanity.
  tags: [cl_setup, always]
  block:

    - name: Setup
      when: cl_setup | bool
      delegate_to: localhost
      run_once: true
      ansible.builtin.import_tasks: setup.yml

    - name: Vars
      ansible.builtin.import_tasks: vars.yml

    - name: Sanity
      when: cl_sanity | bool
      delegate_to: localhost
      run_once: true
      ansible.builtin.import_tasks: sanity.yml

- name: Debug
  when: cl_debug | bool
  tags: cl_debug
  ansible.builtin.import_tasks: debug.yml

- name: Packages
  when: cl_install | bool
  tags: cl_packages
  ansible.builtin.import_tasks: packages.yml

- name: States
  tags: cl_states
  ansible.builtin.import_tasks: states.yml

- name: Files
  tags: cl_files
  ansible.builtin.import_tasks: files.yml

- name: Services
  tags: cl_services
  ansible.builtin.import_tasks: services.yml

# EOF
