---

- name: "sanity: Directories to assemble data from must exist"
  block:
    - name: "sanity: Directories to assemble data from must exist"
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
      vars:
        msg: |-
          Directories to assemble data from do not exist. End of host.
          Hint: Double check existence of the directories
          {{ cl_handlersd_dir }}
          {{ cl_packagesd_dir }}
          {{ cl_statesd_dir }}
          {{ cl_servicesd_dir }}
          {{ cl_filesd_dir }}
    - name: "sanity: End of host"
      meta: end_host
  when:
    - cl_handlersd_dir is not exists or
      cl_packagesd_dir is not exists or
      cl_statesd_dir is not exists or
      cl_servicesd_dir is not exists or
      cl_filesd_dir is not exists

- name: "sanity: Check mode not possible without assembled data"
  block:
    - name: "sanity: Check mode not possible without assembled data"
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
      vars:
        msg: |-
          Check mode not possible without assembled data. End of host.
          Hint: Assemble the variables first.
          Run: ansible-playbook playbook.yml -t cl_vars
    - name: "sanity: End of host"
      ansible.builtin.meta: end_host
  when:
    - ansible_check_mode
    - cl_packagesd is not exists or
      cl_statesd is not exists or
      cl_servicesd is not exists or
      cl_filesd is not exists

# EOF
...
