---

# FreeBSD -----------------------------------------------------------------
- name: "services: FreeBSD"
  block:

    - name: "services: Enable service in rc.conf FreeBSD"
      lineinfile:
        dest: "/etc/rc.conf"
        regexp: "^\\s*{{ item.value.name }}_enable\\s*="
        line: "{{ item.value.name }}_enable=\"YES\""
        backup: "{{ cl_backup }}"
      loop: "{{ cl_services|dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      when: "item.value.enabled|default(true)|bool"

    - name: "services: Disable service in rc.conf FreeBSD"
      lineinfile:
        dest: "/etc/rc.conf"
        regexp: "^\\s*{{ item.value.name }}_enable\\s*="
        line: "{{ item.value.name }}_enable=\"NO\""
        backup: "{{ cl_backup }}"
      loop: "{{ cl_services|dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      when: "not item.value.enabled|default(true)|bool"

  when: "ansible_os_family == 'FreeBSD'"

# All ---------------------------------------------------------------------
- name: "services: Manage services"
  block:

    - name: "services: Manage services"
      service:
        name: "{{ item.value.name }}"
        state: "{{ item.value.state|default('started') }}"
        enabled: "{{ item.value.enabled|default(true) }}"
      loop: "{{ cl_services|dict2items }}"
      loop_control:
        label: "{{ item.key }}"

  when: "ansible_os_family == 'RedHat' or
         ansible_os_family == 'Debian' or
         ansible_os_family == 'FreeBSD'"

# EOF
...
