---

- name: "states: Debug"
  debug:
    msg: "{{ cl_states }}"
  when: cl_debug|bool

- name: "states: Apply states"
  file:
    path: "{{ item.value.path }}"
    state: "{{ item.value.state|default(omit) }}"
    src: "{{ item.value.src|default(omit) }}"
    owner: "{{ item.value.owner|default(omit) }}"
    group: "{{ item.value.group|default(omit) }}"
    mode: "{{ item.value.mode|default(omit) }}"
    attributes: "{{ item.value.attributes|default(omit) }}"
    recurse: "{{ item.value.recurse|default(omit) }}"
    force: "{{ item.value.force|default(omit) }}"
    follow: "{{ item.value.follow|default(omit) }}"
    access_time: "{{ item.value.access_time|default(omit) }}"
    access_time_format: "{{ item.value.access_time_format|default(omit) }}"
    modification_time: "{{ item.value.modification_time|default(omit) }}"
    modification_time_format: "{{ item.value.modification_time_format|default(omit) }}"
    unsafe_writes: "{{ item.value.unsafe_writes|default(omit) }}"
  loop: "{{ cl_states|dict2items }}"
  loop_control:
    label: "{{ item.value.path }}"

# EOF
...
