---

- name: "states: Debug"
  ansible.builtin.debug:
    msg: "{{ cl_states }}"
  when: cl_debug|bool

- name: "states: Apply unmount states"
  ansible.posix.mount:
    path: "{{ item.value.path }}"
    state: "{{ item.value.state|default('absent') }}"
    backup: "{{ item.value.backup|default(omit) }}"
    boot: "{{ item.value.boot|default(omit) }}"
    dump: "{{ item.value.dump|default(omit) }}"
    fstab: "{{ item.value.fstab|default(omit) }}"
    opts: "{{ item.value.opts|default(omit) }}"
    passno: "{{ item.value.passno|default(omit) }}"
    src: "{{ item.value.src|default(omit) }}"
  loop: "{{ cl_states|dict2items }}"
  loop_control:
    label: "{{ item.value.path }}"
  when: item.value.state|default('absent') in cl_states_unmount

- name: "states: Apply file states"
  ansible.builtin.file:
    path: "{{ item.value.path }}"
    state: "{{ item.value.state|default(omit) }}"
    src: "{{ item.value.src|default(omit) }}"
    owner: "{{ item.value.owner|default(omit) }}"
    group: "{{ item.value.group|default(omit) }}"
    mode: "{{ item.value.mode|default(omit) }}"
    attributes: "{{ item.value.attributes|default(omit) }}"
    recurse: "{{ item.value.recurse|default(omit) }}"
    force: "{{ item.value.force|default(omit) }}"
    follow: "{{ item.value.follow|default(omit) }}"
    access_time: "{{ item.value.access_time|default(omit) }}"
    access_time_format: "{{ item.value.access_time_format|default(omit) }}"
    modification_time: "{{ item.value.modification_time|default(omit) }}"
    modification_time_format: "{{ item.value.modification_time_format|default(omit) }}"
    unsafe_writes: "{{ item.value.unsafe_writes|default(omit) }}"
  loop: "{{ cl_states|dict2items }}"
  loop_control:
    label: "{{ item.value.path }}"
  when: item.value.state|default('file') in cl_states_file

- name: "states: Apply mount states"
  ansible.posix.mount:
    path: "{{ item.value.path }}"
    state: "{{ item.value.state }}"
    backup: "{{ item.value.backup|default(omit) }}"
    boot: "{{ item.value.boot|default(omit) }}"
    dump: "{{ item.value.dump|default(omit) }}"
    fstab: "{{ item.value.fstab|default(omit) }}"
    opts: "{{ item.value.opts|default(omit) }}"
    passno: "{{ item.value.passno|default(omit) }}"
    src: "{{ item.value.src|default(omit) }}"
  loop: "{{ cl_states|dict2items }}"
  loop_control:
    label: "{{ item.value.path }}"
  when: item.value.state|default('absent') in cl_states_mount

# EOF
...
