---
- name: Assemble services
  delegate_to: localhost

  block:
    - name: "Vars-services: Delete {{ cl_servicesd }}"
      ansible.builtin.file:
        state: absent
        path: "{{ cl_servicesd }}"
      when: cl_all_delete|bool or cl_servicesd_delete|bool

    - name: "Vars-services: Assemble services to {{ cl_servicesd }}"
      ansible.builtin.assemble:
        regexp: "{{ cl_assemble_regexp }}"
        src: "{{ cl_servicesd_dir }}"
        dest: "{{ cl_servicesd }}"
        owner: "{{ cl_dira_owner | default(omit) }}"
        group: "{{ cl_dira_group | default(omit) }}"
        mode: "{{ cl_dira_fmode }}"
        validate: "{{ cl_assemble_validate | default(omit, true) }}"

  rescue:

    - name: "Vars-services: Failed assemble services to {{ cl_servicesd }}"
      ansible.builtin.debug:
        msg: |-
          [ERR] Can not assemble services. End of play.
          {{ ansible_failed_result }}

    - name: "Vars-services: End of play"
      ansible.builtin.meta: end_play
- name: "Vars-services: Include files from {{ cl_servicesd ~ ' to cl_cervicesd_items' }}"
  ansible.builtin.include_vars:
    file: "{{ cl_servicesd }}"
    name: cl_servicesd_items

- name: "Vars-services: Combine cl_services with cl_servicesd_items"
  ansible.builtin.set_fact:
    cl_services: "{{ cl_services | combine(cl_servicesd_items | default({})) }}"

- name: "Vars-services: Debug"
  ansible.builtin.debug:
    var: cl_services
  when: cl_debug|bool

# EOF
