---

- name: "vars: Debug"
  vars:
    msg: |
      cl_handlersd_dir [{{ cl_handlersd_dir }}]
      cl_packagesd_dir [{{ cl_packagesd_dir }}]
      cl_servicesd_dir [{{ cl_servicesd_dir }}]
      cl_filesd_dir [{{ cl_filesd_dir }}]
      cl_dira [{{ cl_dira }}]
      cl_handlersd [{{ cl_handlersd }}]
      cl_packagesd [{{ cl_packagesd }}]
      cl_servicesd [{{ cl_servicesd }}]
      cl_filesd [{{ cl_filesd }}]
  debug:
    msg: "{{ msg.split('\n') }}"

- name: "vars: Packages"
  import_tasks: vars-packages.yml

- name: "vars: Services"
  import_tasks: vars-services.yml

- name: "vars: Files"
  import_tasks: vars-files.yml

# EOF
...
