---

- name: "vars-packages: Assemble packages to {{ cl_packagesd }}"
  ansible.builtin.assemble:
    regexp: "{{ cl_assemble_regexp }}"
    src: "{{ cl_packagesd_dir }}"
    dest: "{{ cl_packagesd }}"
    owner: "{{ cl_dira_owner|default(omit) }}"
    group: "{{ cl_dira_group|default(omit) }}"
    mode: "{{ cl_dira_fmode }}"
    validate: "{{ cl_assemble_validate|default(omit) }}"
  delegate_to: localhost

- name: "vars-packages: Include files from {{ cl_packagesd }} to cl_packagesd_items"
  ansible.builtin.include_vars:
    file: "{{ cl_packagesd }}"
    name: cl_packagesd_items

- name: "vars-packages: Combine cl_packages with cl_packagesd_items"
  ansible.builtin.set_fact:
    cl_packages: "{{ cl_packages|combine(cl_packagesd_items|default({})) }}"

- name: "vars-packages: Debug"
  ansible.builtin.debug:
    var: cl_packages
  when: cl_debug|bool

# TODO: sort|unique list of packages/ports

# EOF
...
