---

- name: Assemble files
  block:

    - name: "vars-files: Delete {{ cl_filesd }}"
      ansible.builtin.file:
        state: absent
        path: "{{ cl_filesd }}"
      when: cl_all_delete|bool or cl_filesd_delete|bool

    - name: "vars-files: Assemble files to {{ cl_filesd }}"
      ansible.builtin.assemble:
        regexp: "{{ cl_assemble_regexp }}"
        src: "{{ cl_filesd_dir }}"
        dest: "{{ cl_filesd }}"
        owner: "{{ cl_dira_owner|default(omit) }}"
        group: "{{ cl_dira_group|default(omit) }}"
        mode: "{{ cl_dira_fmode }}"
        validate: "{{ cl_assemble_validate|default(omit, true) }}"

  rescue:

    - name: "vars-files: Assemble files to {{ cl_filesd }} failed"
      ansible.builtin.debug:
        msg: |-
          [ERR] Can not assemble files. End of play.
          {{ ansible_failed_result }}

    - name: "vars-files: End of play"
      meta: end_play

  delegate_to: localhost

- name: "vars-files: Include files from {{ cl_filesd }} to cl_filesd_items"
  ansible.builtin.include_vars:
    file: "{{ cl_filesd }}"
    name: cl_filesd_items

- name: "vars-files: Combine cl_files with cl_filesd_items"
  ansible.builtin.set_fact:
    cl_files: "{{ cl_files|combine(cl_filesd_items|default({})) }}"

- name: "vars-files: Debug"
  ansible.builtin.debug:
    var: cl_files
  when: cl_debug|bool

# EOF
...
