---

- name: Assemble packages
  block:

    - name: "vars-packages: Delete {{ cl_packagesd }}"
      ansible.builtin.file:
        state: absent
        path: "{{ cl_packagesd }}"
      when: cl_all_delete|bool or cl_packagesd_delete|bool

    - name: "vars-packages: Assemble packages to {{ cl_packagesd }}"
      ansible.builtin.assemble:
        regexp: "{{ cl_assemble_regexp }}"
        src: "{{ cl_packagesd_dir }}"
        dest: "{{ cl_packagesd }}"
        owner: "{{ cl_dira_owner|default(omit) }}"
        group: "{{ cl_dira_group|default(omit) }}"
        mode: "{{ cl_dira_fmode }}"
        validate: "{{ cl_assemble_validate|default(omit, true) }}"

  rescue:

    - name: "vars-packages: Assemble packages to {{ cl_packagesd }} failed"
      ansible.builtin.debug:
        msg: |-
          [ERR] Can not assemble packages. End of play.
          {{ ansible_failed_result }}

    - name: "vars-packages: End of play"
      meta: end_play

  delegate_to: localhost

- name: "vars-packages: Include files from {{ cl_packagesd }} to cl_packagesd_items"
  ansible.builtin.include_vars:
    file: "{{ cl_packagesd }}"
    name: cl_packagesd_items

- name: "vars-packages: Combine cl_packages with cl_packagesd_items"
  ansible.builtin.set_fact:
    cl_packages: "{{ cl_packages|combine(cl_packagesd_items|default({})) }}"

- name: "vars-packages: Debug"
  ansible.builtin.debug:
    var: cl_packages
  when: cl_debug|bool

# TODO: sort|unique list of packages/ports

# EOF
...
