---

- name: "vars-handlers: Assemble handlers to {{ cl_handlersd }}"
  assemble:
    regexp: "{{ cl_assemble_regexp }}"
    src: "{{ cl_handlersd_dir }}"
    dest: "{{ cl_handlersd }}"
    owner: "{{ cl_dira_owner|default(omit) }}"
    group: "{{ cl_dira_group|default(omit) }}"
    mode: "{{ cl_dira_fmode }}"
    validate: "{{ cl_assemble_validate|default(omit) }}"

- name: "vars-handlers: Include files from {{ cl_handlersd }} to cl_handlersd_items"
  include_vars:
    file: "{{ cl_handlersd }}"
    name: cl_handlersd_items

- name: "vars-handlers: Combine cl_handlers with cl_handlersd_items"
  set_fact:
    cl_handlers: "{{ cl_handlers|combine(cl_handlersd_items|default({})) }}"

- name: "vars-handlers: Debug"
  debug:
    var: cl_handlers
  when: cl_debug|bool

# EOF
...
