---

- name: "vars: Debug"
  vars:
    msg: |-
      cl_packagesd_dir: {{ cl_packagesd_dir }}
      cl_statesd_dir: {{ cl_statesd_dir }}
      cl_servicesd_dir: {{ cl_servicesd_dir }}
      cl_filesd_dir: {{ cl_filesd_dir }}

      cl_dira: {{ cl_dira }}
      cl_packagesd: {{ cl_packagesd }}
      cl_statesd: {{ cl_statesd }}
      cl_servicesd: {{ cl_servicesd }}
      cl_filesd: {{ cl_filesd }}

      cl_all_delete: {{ cl_all_delete }}
      cl_packagesd_delete: {{ cl_packagesd_delete }}
      cl_servicesd_delete: {{ cl_servicesd_delete }}
      cl_filesd_delete: {{ cl_filesd_delete }}
      cl_statesd_delete: {{ cl_statesd_delete }}

      cl_assemble_validate: {{ cl_assemble_validate|d(omit, true) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: cl_debug|bool

- name: "vars: Packages"
  ansible.builtin.import_tasks: vars-packages.yml
  tags: cl_vars_packages

- name: "vars: States"
  ansible.builtin.import_tasks: vars-states.yml
  tags: cl_vars_states

- name: "vars: Services"
  ansible.builtin.import_tasks: vars-services.yml
  tags: cl_vars_services

- name: "vars: Files"
  ansible.builtin.import_tasks: vars-files.yml
  tags: cl_vars_files

# EOF
...
