---

- name: "vars-services: Assemble services to {{ cl_servicesd }}"
  ansible.builtin.assemble:
    regexp: "{{ cl_assemble_regexp }}"
    src: "{{ cl_servicesd_dir }}"
    dest: "{{ cl_servicesd }}"
    owner: "{{ cl_dira_owner|default(omit) }}"
    group: "{{ cl_dira_group|default(omit) }}"
    mode: "{{ cl_dira_fmode }}"
    validate: "{{ cl_assemble_validate|default(omit) }}"
  delegate_to: localhost

- name: "vars-services: Include files from {{ cl_servicesd }} to cl_cervicesd_items"
  ansible.builtin.include_vars:
    file: "{{ cl_servicesd }}"
    name: cl_servicesd_items

- name: "vars-services: Combine cl_services with cl_servicesd_items"
  ansible.builtin.set_fact:
    cl_services: "{{ cl_services|combine(cl_servicesd_items|default({})) }}"

- name: "vars-services: Debug"
  ansible.builtin.debug:
    var: cl_services
  when: cl_debug|bool

# EOF
...
