---
ssh_config:
  path: '/scratch/etc/ssh/ssh_config'
  create: true
  owner: 'admin'
  group: 'admin'
  mode: 'u=rw,g=r,o=r'
  blocks:
    - marker: 'srv1.example.com'
      block: |2
        Host srv1.example.com
            Protocol 2
            ForwardAgent no
