---
sshd_config:
  path: '/scratch/etc/ssh/sshd_config'
  create: true
  owner: 'admin'
  group: 'admin'
  mode: 'u=rw,g=r,o=r'
  lines:
    - {regexp: '^Ciphers ', line: 'Ciphers aes192-ctr'}
  handlers:
    - 'sshd reload'
