---

- hosts: localhost
  gather_facts: false

  tasks:

    - include_vars: templates/annotation.yml
    - template:
        src: templates/annotation.rst.j2
        dest: source/annotation.rst

    - include_vars: templates/examples.yml
    - template:
        src: templates/examples.rst.j2
        dest: source/examples.rst

# EOF
...
