---

# Dragonfly Mail Agent
# https://wiki.mageia.org/en/Dma_Dragonfly_Mail_Agent

# NEVER USE PLAINTEXT PASSWORD. USE VAULT INSTEAD
admin_client_password_mail_example_com: "PASSWORD"

# conf-light/files.d/dma-aliases
cl_dma_aliases:
  - {regexp: '^root:(.*)$', line: 'root: admin@example.com'}
  - {regexp: '^admin:(.*)$', line: 'admin: admin@example.com'}

# conf-light/files.d/dma-dmaconf
cl_dma_smarthost: 'mail.example.com'
cl_dma_port: '587'
cl_dma_authpath: '/usr/local/etc/dma/auth.conf'
cl_dma_aliasespath: '/usr/local/etc/dma/aliases'
cl_dma_masquerade: 'admin@example.com'

# conf-light/files.d/dma-authconf
cl_dma_authconf:
  - 'admin|mail.example.com:{{ admin_client_password_mail_example_com }}'

# conf-light/files.d/mailerconf
cl_mailerconf:
  - 'sendmail      /usr/local/libexec/dma'
  - 'mailq         /usr/local/libexec/dma'
  - 'newaliases    /usr/local/libexec/dma'
  - 'rmail         /usr/local/libexec/dma'

# conf-light/files.d/rcrconf
cl_rcconf_sendmail_enable: 'NO'
cl_rcconf_sendmail_submit_enable: 'NO'
cl_rcconf_sendmail_outbound_enable: 'NO'
cl_rcconf_sendmail_msp_queue_enable: 'NO'

# Services
cl_service_sendmail_enable: false
cl_service_sendmail_state: 'stopped'

# EOF
...
